### PR TITLE
Explicit help for unknown tags error

### PR DESCRIPTION
**Pull request by fjorba**
This is my proposal to help newcomers that face the mysterious unknown_tag error.  Thanks @xhero for writing a first draft in #843.

I know my proposal only fixes the English text, but first, it needs your approval, and second, I'm still not familiarised with Gems I18N and how new texts are propagated and synced in other languages.

### CODE REVIEW

**Comment by xhero** [comment]
I think it is a good idea! But I would place the message in the logfile, because it happens quite often in imported data that there are unconfigured tags and we could leave the full message for the developers, as users generally don't have access to the backend.

**Comment by fjorba** [comment]
As a newcomer, including into the world of Rails, keeping track of everything is overwhelming. Obviously, the first thing you see and read is the screen. The current message is too terse and it does not help. As a matter of fact, without your help in #843, most likely I would have never understood what was going on.

So, if you would like to add this message to the log file, please do so. But, to help newcomers, I strongly believe that displaying on the screen is a good thing, and I'd like to keep it there, because most likely I will make errors again, and this message helps me.

**Comment by xhero** [comment]
My only reserve to add a long error message is that in the (hopefully rare) case of an unknown field (it can happen in case of imported data) our users are generally not very happy to have long multi-line messages on the screen, that's why these "for the administrator" errors tend to be quite terse.
On the other hand I do understand your concern (and it is something I stumble upon quite often with new software). We could probably either add it to the docs or make a "verbose" mode for Muscat that gives more information in the error messages.

**Comment by fjorba** [comment]
It depends on the use case. In my case, it is not rare, but common, as I'm taking the advantage that Muscat allows for different cataloguing templates, and the error can popup in so many different places. I took me so many hours (thanks git grep!) to find out that the 240 tag was hidden in /config/marc/#{RISM::MARC}/source/#{record_type}.marc.  For me it is a configuring and debugging aid.

Maybe this message could point to some external help document?  Something like: Please read the unknown fields in the error messages of the configuration guide?

**Comment by fjorba** [comment]
I'm closing it because newer Muscat releases already display helpful messages for unknown tags (thanks!).

**Pull request closed without merging**
