### PR TITLE
Develop sru index

### PR DESCRIPTION
**Pull request by HirschSt**
Because indexing of 100$a in sources was reconfigured, SRU configuration is updated

### CODE REVIEW

**Comment by ahankinson** [comment]
There are a bunch of schema changes in this PR as well. Should they be there?

**Comment by HirschSt** [comment]
We can discuss this again on Wednesday meeting

**Comment by xhero** [comment]
Can't you just do
`git checkout -- db/schema.rb`
perfore pushing to the PR?

**Comment by xhero** [comment]
@HirschSt could you please modify the PR so it has no schema.db? Since it does not touch the database I think it does not need to be here in the first place. This way I can merge it and have it in 9.3.1.

**Comment by lpugin** [comment]
@HirschSt it seems that your `schema.rb` is not up-to-date. It still contains some tables that do not exist any more. See `crono_jobs` deleted in [this migration](https://github.com/rism-digital/muscat/blob/develop/db/migrate/20230124101722_delete_unused_crono_jobs.rb)

**Pull request closed without merging**
