### PR TITLE
Rename description to title in publications

### PR DESCRIPTION
**Pull request by fjorba**
As part of the publications reorganisation, change the old name description
to title. Perform the database migration and change all occurences.

Please note that in this commit there is no db/schema.rb due to a local
mismatch.  Please add in after performing 'rails db:migrate'.  Thanks.

### CODE REVIEW

**Comment by fjorba** [comment]
Part of #1028, and #626

**Comment by xhero** [comment]
It looks ok to me, we need to do a bit of testing to make sure all the references are caught, I propose to do this in 7.2 so we are not pressed, since 7.1 should come quite soon.

**Comment by fjorba** [comment]
Understood.  While working on this, I've come across some name variables and methods not yet changed to short_name (#1027). Is this change going to be included in 7.1? Because I think I'd better fix it in the same release.

**Comment by fjorba** [comment]
Hello, @xhero, is there a chance to push this patch? I'm experiencing some errors regarding a mismatch between title and description in the Publications model, and my guess is that it will be easier if we complete this transition, as now it is difficult to know what is done and what is left.

Thanks.

**Comment by xhero** [comment]
I merged this patch but I would prefer to avoid patches like this one in the future unless these is a pressing need for an important reason to rename a field on the database, since a modification like this touches many different parts of the system and can lead to some unexpected behaivour which is difficult to test. At the same time, it bings no real improvement to the system, as the db field name is used only internally.

**Comment by fjorba** [comment]
I understand, and it makes sense.  I'll take it into account, thanks for the explanation.

**Pull request merged**
