### PR TITLE
Exclude linked $0 fields from import everywhere

### PR DESCRIPTION
**Pull request by HirschSt**

### CODE REVIEW

**Comment by fjorba** [comment]
I have been working during the last weeks on an (external) script to identify the right authority record for persons (#1176) or other authorities (#1175), using external indices, and assigning the right $0 to them.  I our case it is needed as we import many records (around 2/3), many of them with Orcids or university department ids (#1196), but the form is not the same we have in our database.  I was rewriting the input records with the local database authority form (given an authorized id) but also adding a $0 to make sure there is no ambiguity in the assignment.

Which is the current algorithm to assign an authority record the right id?  I'm afraid that without the input $0 would be no certainty about the assignment.

A possible workaround would be to create a command-line option (#1160)

**Comment by ahankinson** [comment]
I believe this change only affects the VIAF import. The MARC records that are being stripped are the responses from the VIAF interface, which is triggered whenever a user tries to import a VIAF record from the admin interface.

**Comment by xhero** [comment]
Yes this is only for VIAF import!

**Comment by fjorba** [comment]
Oh great. I misunderstood the _everywhere_ word, sorry.

**Comment by xhero** [comment]
Wrong button sorry

**Pull request merged**
