### PR TITLE
Allow items to be added and removed from folders

### LINKED ISSUE #931: Add items to folders from full record view
I would like the ability to add items to folders from the full record view.

### PR DESCRIPTION
**Pull request by fjorba**
Currently the only way to add items to folders is via a batch selection form a list created in the list view.  This patch allows to add and remove them from the full record view.  Closes #931.

Thanks to @ivan-mr from @CodiTramuntana for his help finding a way of doing it following the Rails conventions.

### CODE REVIEW

**Comment by fjorba** [comment]
I'm unsure how to add the new the translation strings in the other languages.  Should I add them using the English text?

**Comment by xhero** [comment]
> I'm unsure how to add the new the translation strings in the other languages. Should I add them using the English text?

I normally add them in ALL CAPS to the other files to signal the translator (me...) that they need translation. Thanks!

**Comment by fjorba** [comment]
Done.

**Comment by ahankinson** [comment]
For the record: You shouldn't modify the non-English translation files. Crowdin manages those, and will copy the english strings into the files automatically, which will then appear in the translation interface.

**Comment by ahankinson** [comment]
Sorry -- just noticed that these are for the admin interface, not the editor. 

(We should really move those labels to Crowdin too... but that's a different issue)

**Comment by xhero** [comment]
> Done

@fjorba did you update the pr? I still see the old lines in this one

**Comment by fjorba** [comment]
> > Done
> 
> @fjorba did you update the pr? I still see the old lines in this one

Yes, I think I did, in a38301cb41335d7afe0cc70a1a0ef34c50d5227d. Or am I missing anything?  Sorry if I haven't understood what to do with translations, as there are conflicting instructions.

**Comment by xhero** [comment]
I think the PR was not updated then, I can't see that branch :)

**Comment by fjorba** [comment]
Oh, yes, you are right. Let's see what I can do...

**Comment by fjorba** [comment]
Is it ok now?

**Comment by fjorba** [comment]
Replaced with v2 in #1438

**Pull request closed without merging**
